name: Master branch updated

env:
  AUTH_TOKEN: ${{ secrets.PAT }}
  EVENT: dependency_updated
  ORG: sergeyspryker
  REPO: to

on:
  push:
    branches:
      - main

jobs:
  trigger-external-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger external repo pr creation
        run: |
          curl -d "{\"event_type\": \"${EVENT}\"}" \
          -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${AUTH_TOKEN}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/${ORG}/${REPO}/dispatches"